"""ACE Framework Layer Definitions for ALEC.

The ACE (Autonomous Cognitive Entity) framework is a 6-layer cognitive architecture
that provides a principled way to organize decision-making, from high-level values
down to low-level task execution.

This module defines the layers, their descriptions, confidence thresholds, and
governance rules for the bullet-based playbook system.
"""

from enum import Enum
from typing import Dict, Literal


class ACELayer(str, Enum):
    """ACE Framework cognitive layers.

    Layers are ordered from highest (most abstract/strategic) to lowest (most concrete/tactical).
    """

    ASPIRATIONAL = "aspirational"
    """Layer 1: Moral reasoning, ethics, values, universal safety constraints.

    This layer defines what the system MUST or MUST NOT do, regardless of context.
    Bullets at this layer are HARD constraints that are NEVER filtered.

    Examples:
    - NEVER output PII (personally identifiable information)
    - Always cite sources for medical claims
    - Do not execute code that modifies production databases
    """

    STRATEGY = "strategy"
    """Layer 2: High-level planning, mission alignment, domain-specific strategies.

    This layer defines strategic approaches and methodologies.

    Examples:
    - For medical queries, prioritize evidence-based recommendations
    - When debugging, start with logs before code changes
    - In customer support, empathize before problem-solving
    """

    AGENT_MODEL = "agent_model"
    """Layer 3: Self-modeling, capability tracking, self-awareness.

    This layer tracks what the system knows about itself and its limitations.

    Examples:
    - I have access to web search but not real-time databases
    - I can read but not write to /production/data
    - My knowledge cutoff is January 2025
    """

    EXECUTIVE = "executive"
    """Layer 4: Dynamic task management, resource allocation, agent creation.

    This layer handles workflow orchestration and task decomposition.

    Examples:
    - For multi-file changes, use Edit tool instead of Write
    - When stuck after 3 attempts, escalate to user
    - Break tasks >5 steps into subtasks
    """

    COGNITIVE = "cognitive"
    """Layer 5: Decision-making, working memory, deliberation.

    This layer handles real-time reasoning and context management.

    Examples:
    - When context >80%, offload to Task agent
    - Verify file existence before editing
    - Quote paths with spaces in shell commands
    """

    TASK = "task"
    """Layer 6: Execution, tool usage, embodiment.

    This layer contains specific tool usage patterns and execution details.

    Examples:
    - Use pytest -v for verbose test output
    - Use HEREDOC for multi-line git commit messages
    - Always use absolute paths in agent threads
    """


# Layer descriptions for documentation and UI display
ACE_LAYER_DESCRIPTIONS: Dict[ACELayer, str] = {
    ACELayer.ASPIRATIONAL: "Moral reasoning, ethics, values, safety constraints",
    ACELayer.STRATEGY: "High-level planning, mission alignment, domain strategies",
    ACELayer.AGENT_MODEL: "Self-modeling, capability tracking, self-awareness",
    ACELayer.EXECUTIVE: "Dynamic task management, resource allocation, agent creation",
    ACELayer.COGNITIVE: "Decision-making, working memory, deliberation",
    ACELayer.TASK: "Execution, tool usage, embodiment"
}


# Default confidence thresholds per layer
# Lower layers (more tactical) can have lower confidence thresholds
# because they're easier to validate and less risky to get wrong
ACE_CONFIDENCE_THRESHOLDS: Dict[ACELayer, float] = {
    ACELayer.ASPIRATIONAL: 1.0,  # Must NEVER be filtered (perfect confidence required)
    ACELayer.STRATEGY: 0.85,     # High confidence for strategic guidance
    ACELayer.AGENT_MODEL: 0.80,  # High confidence for self-awareness
    ACELayer.EXECUTIVE: 0.75,    # Moderate-high for workflow decisions
    ACELayer.COGNITIVE: 0.70,    # Moderate for real-time reasoning
    ACELayer.TASK: 0.65          # Lower for specific tool patterns (easier to validate)
}


# Constraint types define whether bullets can be filtered
ConstraintType = Literal["HARD", "SOFT"]

"""HARD: Never filtered, always included (typically aspirational layer).
SOFT: May be filtered based on redundancy, confidence, or relevance.
"""


# Provenance tracking for bullets
ProvenanceType = Literal["human", "pattern", "agent", "reflection"]

"""Tracks the origin of a bullet:
- human: Manually created by a developer or domain expert
- pattern: Extracted from observed decision patterns
- agent: Generated by an agent during execution
- reflection: Created by a reflector agent analyzing sessions
"""


def get_layer_description(layer: ACELayer) -> str:
    """Get human-readable description of an ACE layer.

    Args:
        layer: The ACE layer to describe

    Returns:
        Description string
    """
    return ACE_LAYER_DESCRIPTIONS[layer]


def get_confidence_threshold(layer: ACELayer) -> float:
    """Get the minimum confidence threshold for a layer.

    Args:
        layer: The ACE layer

    Returns:
        Minimum confidence threshold (0.0 to 1.0)
    """
    return ACE_CONFIDENCE_THRESHOLDS[layer]


def is_hard_constraint(layer: ACELayer) -> bool:
    """Check if a layer typically contains hard constraints.

    Args:
        layer: The ACE layer to check

    Returns:
        True if the layer typically has HARD constraints
    """
    return layer == ACELayer.ASPIRATIONAL


def validate_layer_assignment(
    layer: ACELayer,
    constraint_type: ConstraintType,
    confidence: float
) -> tuple[bool, str | None]:
    """Validate that a bullet's ACE layer assignment is appropriate.

    Args:
        layer: The assigned ACE layer
        constraint_type: HARD or SOFT
        confidence: Confidence score (0.0 to 1.0)

    Returns:
        (is_valid, error_message)
        If valid: (True, None)
        If invalid: (False, "reason why invalid")
    """
    # Aspirational layer should always be HARD
    if layer == ACELayer.ASPIRATIONAL and constraint_type != "HARD":
        return False, "Aspirational layer bullets must be HARD constraints"

    # HARD constraints should typically be in aspirational or strategy layers
    if constraint_type == "HARD" and layer not in [ACELayer.ASPIRATIONAL, ACELayer.STRATEGY]:
        return False, f"HARD constraints should typically be in aspirational or strategy layers, not {layer}"

    # Confidence should meet layer threshold
    threshold = get_confidence_threshold(layer)
    if confidence < threshold:
        return False, f"Confidence {confidence} below threshold {threshold} for layer {layer}"

    return True, None


def should_propagate_upward(layer: ACELayer) -> bool:
    """Determine if insights at this layer should propagate upward.

    Upward propagation means insights from lower layers can influence higher layers.
    For example, repeated task-level failures might indicate a need for strategic change.

    Args:
        layer: The ACE layer

    Returns:
        True if this layer's insights should be considered for upward propagation
    """
    # All layers can propagate upward, but lower layers require more evidence
    return True


def should_propagate_downward(layer: ACELayer) -> bool:
    """Determine if constraints at this layer must propagate downward.

    Downward propagation means constraints from higher layers must be enforced
    at all lower layers. Aspirational constraints always propagate down.

    Args:
        layer: The ACE layer

    Returns:
        True if this layer's constraints must be enforced at lower layers
    """
    # Aspirational and strategy layers always propagate down
    return layer in [ACELayer.ASPIRATIONAL, ACELayer.STRATEGY]
