"""Shared assessment types for bullet effectiveness and task outcomes.

These models are used across the effectiveness reflector, curator, and
other services that track bullet quality and task results.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


class AssessmentRating(str, Enum):
    """Rating for bullet effectiveness assessment.

    Attributes:
        HELPFUL: Bullet positively contributed to task completion
        NEUTRAL: Bullet had no significant impact on outcome
        HARMFUL: Bullet negatively impacted task completion
    """
    HELPFUL = "helpful"
    NEUTRAL = "neutral"
    HARMFUL = "harmful"


class BulletAssessment(BaseModel):
    """Assessment result for a single bullet's effectiveness.

    Generated by the effectiveness reflector when evaluating how well
    a bullet contributed to the LLM response quality.

    Attributes:
        bullet_id: Unique identifier for the assessed bullet
        rating: Effectiveness rating (helpful/neutral/harmful)
        reasoning: Explanation of why the bullet received this rating
        confidence: Confidence level of the assessment (0-1)
        assessed_at: Timestamp when assessment was made
    """
    bullet_id: str = Field(
        ...,
        description="Unique identifier for the assessed bullet"
    )
    rating: AssessmentRating = Field(
        ...,
        description="Effectiveness rating for the bullet"
    )
    reasoning: str = Field(
        ...,
        description="Explanation of the assessment decision"
    )
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence level of the assessment (0-1)"
    )
    assessed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when assessment was made"
    )


class TaskOutcome(BaseModel):
    """Outcome record for a completed task within a session.

    Used to track task-level success metrics and correlate with
    bullet usage for learning effectiveness.

    Attributes:
        session_id: Session in which the task was performed
        task_id: Unique identifier for the task
        success: Whether the task completed successfully
        iterations: Number of attempts before completion
        error_message: Error message if task failed
        bullets_used: List of bullet IDs used during the task
        completed_at: Timestamp when task completed
    """
    session_id: UUID = Field(
        ...,
        description="Session in which the task was performed"
    )
    task_id: str = Field(
        ...,
        description="Unique identifier for the task"
    )
    success: bool = Field(
        ...,
        description="Whether the task completed successfully"
    )
    iterations: int = Field(
        ...,
        ge=1,
        description="Number of attempts before completion"
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error message if task failed"
    )
    bullets_used: list[str] = Field(
        default_factory=list,
        description="List of bullet IDs used during the task"
    )
    completed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when task completed"
    )
