"""Shared event schemas for ALEC system events.

This module defines Pydantic models for all system events following the
standard event schema documented in ARCHITECTURE.md.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator


class BaseEvent(BaseModel):
    """Base class for all system events.

    All events in ALEC follow this standard schema with auto-generated
    event_id and timestamp fields.
    """

    event_id: UUID = Field(default_factory=uuid4, description="Unique event identifier")
    event_type: str = Field(..., description="Type of event (e.g., 'session.created')")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Event timestamp in UTC"
    )
    correlation_id: Optional[UUID] = Field(
        default=None,
        description="Correlation ID for tracing related events"
    )

    model_config = {
        "json_encoders": {
            UUID: str,
            datetime: lambda v: v.isoformat(),
        },
        "populate_by_name": True,
    }

    def model_dump_json_safe(self) -> Dict[str, Any]:
        """Return a JSON-serializable dictionary with proper type conversions.

        Converts UUIDs to strings and datetimes to ISO format strings.
        """
        data = self.model_dump()
        result: Dict[str, Any] = self._convert_for_json(data)
        return result

    def _convert_for_json(self, obj: Any) -> Any:
        """Recursively convert non-JSON-serializable types."""
        if isinstance(obj, UUID):
            return str(obj)
        elif isinstance(obj, datetime):
            return obj.isoformat()
        elif isinstance(obj, dict):
            return {k: self._convert_for_json(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [self._convert_for_json(item) for item in obj]
        return obj


class SessionCreatedEvent(BaseEvent):
    """Event emitted when a new session is created.

    Triggers bullet generation by the Bullet Reflector.
    """

    event_type: Literal["session.created"] = "session.created"
    session_id: UUID = Field(..., description="Unique session identifier")
    first_message: str = Field(..., description="User's initial message for the session")
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional metadata about the session"
    )


class LLMResponseReceivedEvent(BaseEvent):
    """Event emitted after receiving a response from the LLM.

    Contains the response, bullets used, and performance metrics.
    Used for effectiveness tracking.
    """

    event_type: Literal["llm.response.received"] = "llm.response.received"
    session_id: UUID = Field(..., description="Session identifier")
    response: str = Field(..., description="LLM response text")
    bullets_used: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of bullets injected into the prompt"
    )
    latency_ms: int = Field(..., ge=0, description="Response latency in milliseconds")
    token_usage: Dict[str, int] = Field(
        ...,
        description="Token usage breakdown (input_tokens, output_tokens)"
    )
    execution_outcome: Dict[str, Any] = Field(
        default_factory=dict,
        description="Outcome of execution (success, iterations, errors)"
    )

    @field_validator("token_usage")
    @classmethod
    def validate_token_usage(cls, v: Dict[str, int]) -> Dict[str, int]:
        """Validate token_usage contains expected keys."""
        if not isinstance(v, dict):
            raise ValueError("token_usage must be a dictionary")
        return v


class BulletEffectivenessEvent(BaseEvent):
    """Event emitted when a bullet's effectiveness is assessed.

    Generated by the Effectiveness Reflector after analyzing
    how a bullet contributed to the LLM response.
    """

    event_type: Literal["bullet.effectiveness"] = "bullet.effectiveness"
    bullet_id: str = Field(..., description="Identifier of the bullet being assessed")
    session_id: str = Field(..., description="Session where bullet was used")
    assessment: Literal["helpful", "neutral", "harmful"] = Field(
        ...,
        description="Effectiveness assessment of the bullet"
    )
    reasoning: str = Field(..., description="LLM reasoning for the assessment")
    bullet_content: str = Field(..., description="Content of the bullet that was assessed")
    bullet_category: str = Field(
        ...,
        description="ACE category (cheat_sheets, constraints, examples, meta_prompts)"
    )


class TaskCompletedEvent(BaseEvent):
    """Event emitted when a task within a session is completed.

    Used for tracking task success rates and learning effectiveness.
    """

    event_type: Literal["task.completed"] = "task.completed"
    session_id: UUID = Field(..., description="Session identifier")
    task_id: str = Field(..., description="Unique task identifier")
    success: bool = Field(..., description="Whether the task completed successfully")
    iterations: int = Field(
        ...,
        ge=0,
        description="Number of iterations to complete the task"
    )
    bullets_used: List[str] = Field(
        default_factory=list,
        description="List of bullet IDs used during task execution"
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error message if task failed"
    )
